alias edit=subl
alias ls="ls -p"
alias s=edit
alias s.="s ."
alias editrc="edit ~/.dotfiles"
alias resource="source ~/.bashrc && echo loaded .bashrc"
alias dev="cd ~/dev"
alias cd..="cd .."
alias g=git
alias gst="git status"
alias glog="git log"
alias npms="npm install --save"
alias npmr="npm run"
alias npmsd="npm install --save-dev"
alias deva="cd ~/dev/agilemd"
