format = """
$username\
$hostname\
$shlvl\
$git_branch\
$git_commit\
$git_state\
$git_status\
$directory\
$docker_context\
$kubernetes\
$package\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$python\
$ruby\
$rust\
$swift\
$terraform\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$line_break\
$character"""

[directory]
truncate_to_repo = true
fish_style_pwd_dir_length = 1

[git_status]
# remove stashed
format = '([\[$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind\]]($style) )'

[package]
disabled = true

# Replace the "❯" symbol in the prompt with "λ"
[character]
success_symbol = ";;"
error_symbol = ";;"

[battery]
full_symbol = ""
charging_symbol = "⚡️ "
discharging_symbol = " "
format = "[$symbol]($style)"
[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 15
style = "bold red"

[aws]
disabled = true

[nodejs]
format = "[$symbol$version]($style) "

[cmd_duration]
min_time = 1_000
show_notifications = false
min_time_to_notify = 5_000

[kubernetes]
disabled = true
style = "blue"
[kubernetes.context_aliases]
"gke_affable-visitor-137123_us-central1-b_cluster-6" = "prod"

[gcloud]
format = '$symbol'

[custom.foo]
command = "echo foo"
when = "true"
disabled = true

[time]
disabled = false
time_format = "%H:%M" # see https://docs.rs/chrono/0.4.7/chrono/format/strftime/index.html